### PR TITLE
Add temporary shell script for automated pages/range selection

### PR DESCRIPTION
**Pull request by marc3l-barraualt**
The shell script added lets you specify a range of pages on a target profile to scrape. It's not anything crazy but kinda useful when going through 17+ pages of stuff.

### CODE REVIEW

**Comment by A-Coom** [comment]
Thanks for the contribution! I would prefer your wrapper script and usage instructions be moved to a subdirectory, so that the primary usage remain platform agnostic. Something along the lines of this:
```
wrappers/
│
├─ debian/
│    ├─ runner_script.sh
│    └─ README.md
│
└─ windows/
     ├─ runner_script.bat
     └─ README.md
```

You don't need to include the Windows wrapper in this pull request, but please move what you've developed into a subdirectory as described and I'll get it merged in.

**Review by A-Coom — CHANGES_REQUESTED** [review]
Thanks for the contribution! I would prefer your wrapper script and usage instructions be moved to a subdirectory, so that the primary usage remain platform agnostic. Something along the lines of this:
```
bin/
│
├─ debian/
│    ├─ runner_script.sh
│    └─ README.md
│
└─ windows/
     ├─ runner_script.bat
     └─ README.md
```
You don't need to include the Windows wrapper in this pull request, but please move what you've developed into a subdirectory as described and I'll get it merged in.

**Comment by marc3l-barraualt** [comment]
Okay, reedited it and put stuff into the sub directory. Thought about adding come more script for doing downloads in parallel by calling the python program with different URLS at the same time, but it might hammer the severs a bit too hard idk.

**Review by A-Coom — APPROVED** [review]

**Comment by A-Coom** [comment]
Thanks, I accept your changes!
Yes, there are sleeps in the Python code to prevent the servers from being unhappy with too much traffic; running multiple instances of the script would most likely cause a failure after several connections. I would like to experiment with orchestrating multiple threads to download more media at once in the future, but there's a fine balance between speed and getting blocked.

**Pull request merged**
